# Markdown Linting Configuration

# Markdown linting rules for architecture documentation
# Uses markdownlint (https://github.com/DavidAnson/markdownlint)

# MD013/line-length - Line length
MD013:
  # Disable line length check for documentation
  # Architecture docs often contain long URLs, code examples, and tables
  enabled: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow inline HTML for advanced formatting
  enabled: false
  allowed_elements:
    - details
    - summary
    - br
    - sup
    - sub

# MD041/first-line-h1 - First line in file should be a top level heading
MD041:
  # Require top-level heading as first line
  enabled: true

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  # Allow duplicate headings in different sections
  siblings_only: true

# MD046/code-block-style - Code block style
MD046:
  # Enforce fenced code blocks (```) over indented
  style: "fenced"

# MD007/ul-indent - Unordered list indentation
MD007:
  # Indent unordered lists by 2 spaces
  indent: 2

# MD030/list-marker-space - Spaces after list markers
MD030:
  # Single space after list marker
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD048/code-fence-style - Code fence style
MD048:
  # Use backticks for code fences
  style: "backtick"
